apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: taskmaster
  labels:
    app: frontend
    tier: presentation
spec:
  type: ClusterIP
  selector:
    app: frontend
    tier: presentation
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
