apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: taskmaster
  labels:
    app: backend
    tier: application
data:
  DB_HOST: postgres-svc.taskmaster.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: tasks
  FLASK_ENV: production
  LOG_LEVEL: INFO
