apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: taskmaster
  labels:
    app: backend
    tier: application
type: Opaque
stringData:
  DB_USER: taskuser
  DB_PASSWORD: taskpass123
  SECRET_KEY: workshop-secret-key-change-in-production
