apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: taskmaster
  labels:
    app: backend
    tier: application
spec:
  type: ClusterIP
  selector:
    app: backend
    tier: application
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  sessionAffinity: None
