apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: taskmaster
  labels:
    app: postgres
    tier: database
type: Opaque
stringData:
  POSTGRES_USER: taskuser
  POSTGRES_PASSWORD: taskpass123
  POSTGRES_DB: tasks
