apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: taskmaster
  labels:
    app: postgres
    tier: database
spec:
  type: ClusterIP
  selector:
    app: postgres
    tier: database
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  sessionAffinity: None
